drop table if exists member CASCADE;
create table member
(
id varchar(255)  generated by default as identity,
password varchar(255) not null,
name varchar(255) not null,
RRN bigint(100) not null unique,
number bigint(100) not null unique ,
primary key (id)

);

--insert into member(id, password, name, number, rrn) values('eunbin', '1234', '이은빈', '1234', '1234');
insert into member(id, password, name, number, RRN) values('huiji', 'asfd', 'huijikim', '1111', '1111');